import re
import os
import threading

def normalize_answer(s):
    """
    Normalize the answer by lowercasing and stripping whitespace/punctuation.
    Simple normalization for "True"/"False" string matching.
    """
    if not isinstance(s, str):
        return ""
    # Lowercase and strip
    s = s.lower().strip()
    # Remove trailing punctuation (like periods) often generated by LLMs
    s = s.rstrip(".")
    return s


# ---------------------------------------------------------------------------
# Module-level step tracker for dynamic negative reward scheduling.
#
# How it works:
#   - The reward function is called once per *sample* by NaiveRewardManager.
#   - Each training step processes a full batch of samples.
#   - We use an environment variable VERL_GLOBAL_STEP (set by the trainer
#     loop) to get the current global step.  If the env-var is not available
#     we fall back to a simple module-level counter that increments every
#     `batch_size` calls (controlled by the `_step_tracker` below).
#   - `total_steps_per_epoch` is the total number of optimizer steps in one
#     epoch.  It can be passed as a kwarg via the config or read from the
#     VERL_TOTAL_STEPS_PER_EPOCH env-var.  If neither is set, we default to
#     250 (adjust to your training setup).
# ---------------------------------------------------------------------------

class _StepTracker:
    """Thread-safe, module-level tracker for the current training step."""

    def __init__(self):
        self._lock = threading.Lock()
        self._call_count = 0        # total calls to compute_score
        self._current_step = 0      # inferred step (call_count // batch_size)
        self._batch_size = None     # auto-detected on first batch
        self._total_steps = None    # total steps per epoch

    # -- public helpers -------------------------------------------------------

    def get_progress(self, total_steps_kwarg=None, batch_size_kwarg=None):
        """Return (current_step, total_steps_per_epoch) as ints.

        Priority for total_steps:
            1. `total_steps_kwarg` passed via reward_kwargs in config
            2. VERL_TOTAL_STEPS_PER_EPOCH environment variable
            3. fallback default (250)

        Priority for current_step:
            1. VERL_GLOBAL_STEP environment variable (set by trainer)
            2. module-level call counter // batch_size
        """
        # --- total steps per epoch ---
        if total_steps_kwarg is not None:
            total_steps = int(total_steps_kwarg)
        elif os.environ.get("VERL_TOTAL_STEPS_PER_EPOCH"):
            total_steps = int(os.environ["VERL_TOTAL_STEPS_PER_EPOCH"])
        else:
            total_steps = 250  # safe default

        # --- current step ---
        env_step = os.environ.get("VERL_GLOBAL_STEP")
        if env_step is not None:
            current_step = int(env_step)
        else:
            # Fallback: derive from call count
            bs = batch_size_kwarg or self._batch_size or 8
            with self._lock:
                current_step = self._call_count // int(bs)

        return current_step, total_steps

    def tick(self):
        """Increment the internal call counter (one call = one sample)."""
        with self._lock:
            self._call_count += 1


_step_tracker = _StepTracker()


def compute_score(solution_str, ground_truth, method="strict", format_score=0.0,
                  score=1.0, **kwargs):
    """
    Lexical reward function for VSR dataset — with **parameterized dynamic negative reward**.

    Identical to `vsr_lexical_dynamic.compute_score` except that the penalty for an
    incorrect / hallucinated answer includes a `k` factor:

        negative_reward = -1 * (1 + k * current_step / total_steps_per_epoch)

    This means:
        • `k` controls how aggressively the penalty scales over time.
        • Early in training the penalty is close to -1.
        • As training progresses the penalty grows toward -(1 + k) → the model is
          progressively incentivised to abstain (say "I don't know") rather than
          hallucinate, pushing expected return lower at high confidence levels.

    Args:
        solution_str: The model's predicted output string.
        ground_truth: The ground truth object (containing the target label).
        method: Not used, kept for signature compatibility.
        format_score: Score for invalid format (not used here).
        score: Score for correct answer (default 1.0).
        **kwargs: Additional keyword arguments.  The following are recognised:
            total_steps_per_epoch (int): Total optimizer steps in one epoch.
            batch_size (int): Number of samples per training step.
            k_factor (float): The multiplication factor for the dynamic penalty.
                Can also be set via VERL_DYNAMIC_PENALTY_K env var.

    Returns:
        dict with keys:
            score (float): The calculated reward.
            accuracy (float): 1.0 if correct, 0.0 otherwise.
            negative_reward (float): the raw dynamic penalty (for logging).
    """

    # -- Tick the module-level counter (one call per sample) --
    _step_tracker.tick()

    # -- Resolve step progress --
    total_steps_kwarg = kwargs.get("total_steps_per_epoch", None)
    batch_size_kwarg = kwargs.get("batch_size", None)
    current_step, total_steps = _step_tracker.get_progress(
        total_steps_kwarg=total_steps_kwarg,
        batch_size_kwarg=batch_size_kwarg,
    )

    # -- Resolve k factor --
    k_factor = kwargs.get("k_factor", None)
    if k_factor is None:
        env_k = os.environ.get("VERL_DYNAMIC_PENALTY_K")
        k_factor = float(env_k) if env_k else 1.0
    else:
        k_factor = float(k_factor)

    # -- Calculate Dynamic Negative Reward --
    # Calculate ratio (can exceed 1.0 if training for multiple epochs)
    progress_ratio = current_step / max(total_steps, 1)
    negative_reward = -1.0 * (1.0 + k_factor * progress_ratio)

    # -- 1. Extract Ground Truth --
    target = ground_truth
    if isinstance(ground_truth, dict):
        target = ground_truth.get("ground_truth", "False")

    # -- 2. Check Format & Extract Answer --
    box_match = re.search(r'/box\[(.*?)\]/', solution_str)
    if box_match:
        answer_to_check = box_match.group(1)
    else:
        # Penalise for missing out the /box[]/ format constraint.
        # Use format_score if it's explicitly a penalty (< 0), otherwise use the dynamic negative_reward.
        penalty = format_score if format_score < 0 else negative_reward
        
        # Logging for format failure
        log_path = "/home/debarpanb1/kalashkala/TruthRL/dynamic_reward_debug.log"
        if not os.path.exists(os.path.dirname(log_path)):
            log_path = "/home/kalashkala/TruthRL/dynamic_reward_debug.log"
        try:
            if os.path.exists(os.path.dirname(log_path)):
                with open(log_path, "a") as f:
                    f.write(f"[REWARD DEBUG K-FACTOR - FORMAT MISSING] step: {current_step}/{total_steps} | penalty: {penalty:.4f}\n")
        except Exception:
            pass
            
        return {'score': penalty, 'accuracy': 0.0, 'negative_reward': negative_reward}

    # -- 3. Normalize Prediction --
    pred_str = normalize_answer(answer_to_check)
    target_str = normalize_answer(target)

    # -- 4. Check for "I don't know" (Safe Refusal) --
    unknown_triggers = ["i don't know", "i dont know", "unsure", "i do not know"]
    if any(trigger in pred_str for trigger in unknown_triggers):
        return {'score': 0.0, 'accuracy': 0.0, 'negative_reward': 0.0}

    # -- 5. Check for Exact Match --
    if pred_str == target_str:
        return {'score': score, 'accuracy': 1.0, 'negative_reward': 0.0}

    # -- 6. Incorrect / Hallucinated Answer --
    # The dynamic negative reward was calculated above.

    # Logging
    log_path = "/home/debarpanb1/kalashkala/TruthRL/dynamic_reward_debug.log"
    # Fallback to current workspace if the original path doesn't exist
    if not os.path.exists(os.path.dirname(log_path)):
        log_path = "/home/kalashkala/TruthRL/dynamic_reward_debug.log"

    try:
        if os.path.exists(os.path.dirname(log_path)):
            with open(log_path, "a") as f:
                f.write(f"[REWARD DEBUG K-FACTOR] step: {current_step}/{total_steps} | ratio: {progress_ratio:.4f} | k: {k_factor:.2f} | neg_reward: {negative_reward:.4f}\n")
    except Exception:
        pass

    return {'score': negative_reward, 'accuracy': 0.0, 'negative_reward': negative_reward}
