
import re

def normalize_answer(s):
    """
    Normalize the answer by lowercasing and stripping whitespace/punctuation.
    Simple normalization for "True"/"False" string matching.
    """
    if not isinstance(s, str):
        return ""
    # Lowercase and strip
    s = s.lower().strip()
    # Remove trailing punctuation (like periods) often generated by LLMs
    s = s.rstrip(".")
    return s

def compute_score(solution_str, ground_truth, method="strict", format_score=-1.0, score=1.0, **kwargs):
    """
    Lexical reward function for VSR dataset.
    
    Args:
        solution_str: The model's predicted output string.
        ground_truth: The ground truth object (containing the target label).
        method: Not used, kept for signature compatibility.
        format_score: Score for invalid format (not used here, effectively -1).
        score: Score for correct answer (default 1.0).
        
    Returns:
        reward (float): 
            +1.0 if prediction matches ground truth exactly.
             0.0 if prediction is "i don't know" (or variation).
            -1.0 if prediction is incorrect or hallucinated.
    """
    
    # 1. Extract Ground Truth
    # The preprocessor stores the label (True/False) in 'reward_model'['ground_truth']
    # But Verl passes the 'data_source' reward_model field. 
    # Depending on how it's unpacked, we might get just the label string or a dict.
    # In 'main_ppo.py', reward_fn is called with `data`.
    # Let's assume standard Verl usage where we extract from the passed structure or it's passed directly.
    # Looking at `truthrl_qa.py`, `ground_truth` seems to be the target value directly if we follow `rl_dataset`.
    # However, to be safe, we'll assume `ground_truth` might be the dict we saved in preprocessing: 
    # {"style": "lexical", "ground_truth": "True"} -> we might need to adjust based on verified input.
    # For now, let's assume `ground_truth` is the target string (e.g., "True").
    
    target = ground_truth
    if isinstance(ground_truth, dict):
        target = ground_truth.get("ground_truth", "False")
    
    # 2. Check Format & Extract Answer
    box_match = re.search(r'/box\[(.*?)\]/', solution_str)
    if box_match:
        answer_to_check = box_match.group(1)
    else:
        # Penalise for missing out the /box[]/ format constraint.
        penalty = format_score if format_score < 0 else -1.0
        return {'score': penalty, 'accuracy': 0.0}
    
    # 3. Normalize Prediction
    pred_str = normalize_answer(answer_to_check)
    target_str = normalize_answer(target)
    
    # 3. Check for "I don't know" (Safe Refusal)
    # Variations: "i don't know", "i dont know", "unsure"
    unknown_triggers = ["i don't know", "i dont know", "unsure", "i do not know"]
    if any(trigger in pred_str for trigger in unknown_triggers):
        return {'score': 0.0, 'accuracy': 0.0}
        
    # 4. Check for Exact Match
    if pred_str == target_str:
        return {'score': score, 'accuracy': 1.0}
    
    # 5. Check for Incorrect Answer (Hallucination)
    # If target is "true" and pred is "false", or vice-versa
    # Or if pred is random gibberish (also punished as -1)
    
    return {'score': -1.0, 'accuracy': 0.0}
